export { buildDashboardModel } from "./builder.js";
export type {
  CrmDashboardRecord,
  DashboardBusinessData,
  DashboardBusinessHealth,
  DashboardBusinessHealthStatus,
  DashboardDatabaseLink,
  DashboardExecutiveSummary,
  DashboardMetric,
  DashboardModel,
  DashboardModuleKey,
  DashboardPriority,
  DashboardPrioritySeverity,
  DashboardWidget,
  FinanceDashboardRecord,
  GameJamsDashboardRecord,
  PortfolioDashboardRecord,
  ProductionMusicDashboardRecord,
  ProjectDashboardRecord,
} from "./types.js";
